[sdl]
fullscreen=false
fulldouble=false
fullresolution=640x480
windowresolution=640x480
output=surface
autolock=false
sensitivity=100
waitonerror=false
priority=higher,normal
mapperfile=mapper.txt
usescancodes=false

[dosbox]
language=
machine=svga_s3
captures=capture
memsize=8

[render]
frameskip=0
aspect=false
scaler=none

[cpu]
core=normal
cputype=386_slow
cycles=1000
cycleup=100
cycledown=100

[mixer]
nosound=false
rate=22050
blocksize=1024
prebuffer=10

[midi]
mpu401=none
mididevice=none

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
mixer=true
oplmode=auto
oplemu=default
oplrate=22050

[gus]
gus=false

[speaker]
pcspeaker=true
pcrate=22050
tandy=auto
tandyrate=22050
disney=false

[joystick]
joysticktype=none
timed=true
autofire=false
swap34=false
buttonwrap=false

[serial]
serial1=dummy
serial2=dummy
serial3=disabled
serial4=disabled

[dos]
xms=true
ems=true
umb=true
keyboardlayout=none

[ipx]
ipx=false

[autoexec]
mount c /mnt/sdcard/MIPS_NATIVE/dosbox_r36sx/drive_c
c:
dir
